### ISSUE TITLE
Gender - (Optional) and Dropdown menu should provide theses options:

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#23]
Gender:
Field should say: Gender - (Optional) and dropdown arrow
Dropdown menu should provide theses options:
Male
Female
Non-binary
Prefer not to respond

provided by the customer 

not stated in the prd but okay to implement

**Comment by Aqurds** [comment]
@Sheerazzafar this is fixed. cc @romangorbunovCB

**Comment by Sheerazzafar** [comment]
@Aqurds verified this issue on latest build and this issue is still not fixed!

**Comment by Sheerazzafar** [comment]
Verified and this issue is fixed now!
