### ISSUE TITLE
Zip Code should be alpha numerical worldwide.

### ISSUE THREAD

**Issue by romangorbunovCB** [crowdbotics-apps/ideapros-llc-viaggi-32125#26]
Home Location:
Zip Code

- Zip Code should be alpha numerical worldwide.
- Current App only allows for numerical, but you it allows for only single digit number

provided by the customer
not stated in the prd, but okay to implement

**Comment by Aqurds** [comment]
@Sheerazzafar this is fixed. cc @romangorbunovCB

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
Verified this issue on latest build and its still happening.
Video: https://www.screencast.com/t/5BYaWaSMjJ

**Comment by romangorbunovCB** [comment]
@Sheerazzafar It is not clear if the issue is remaining judging the video. We need to have the entry inputs to be alphanumeric. Please, confirm.

**Comment by Aqurds** [comment]
@Sheerazzafar client wants the zip code should be alphanumerical and in your video, the keyboard is alphanumerical, isn't it?

**Comment by romangorbunovCB** [comment]
@asim-crowdbotics pls proceed with these issues as well

**Comment by asim-crowdbotics** [comment]
![Screenshot_1665499532](https://user-images.githubusercontent.com/111840959/195123887-98f9e640-d3c1-4db9-b890-1bb6dec5e8fd.png)

**Comment by romangorbunovCB** [comment]
@Sheerazzafar pls confirm and update the ticket. thank you

**Comment by Sheerazzafar** [comment]
Verified this issue and its fixed!
