### ISSUE TITLE
Title: Forgot Password text (g) is getting cut-off

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#3]
Screen Name: Sign In
Build version: 1.0 

Actual result: Forgot Password text (g) is getting cut-off.
Expected result: App should not show any cut-off issue.

Refer this screenshot/video: https://www.screencast.com/t/pNQulcgM13gA

**Comment by Aqurds** [comment]
@Sheerazzafar this bug is fixed
![forgot_password_viaggio](https://user-images.githubusercontent.com/39187898/178905867-2948a1ae-c3e6-45ac-aa54-8a70a5bd23f3.png)
.

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
I have verified this issue on latest build and this issue is still happening on real mobile device.
Device: Samsung s9 Plus

**Comment by Aqurds** [comment]
@Sheerazzafar It's confusing :) I have made some adjustments. Would you please test now?

**Comment by Sheerazzafar** [comment]
Verified this issue on latest build and this issue is fixed now!
