### ISSUE TITLE
 Title: Terms and Condition and Privacy policy links are not functional

### ISSUE THREAD

**Issue by Sheerazzafar** [crowdbotics-apps/ideapros-llc-viaggi-32125#5]
Screen Name: Sign Up
Build version: 1.0 

Actual result: Terms and Condition and Privacy policy links are not functional.
Expected result: Ideally terms and Condition and Privacy policy links should be functional and after taping on these links app should take user to relevant screens.
Refer this screenshot/video: https://www.screencast.com/t/MziUoWZd 
Refer this Figma: https://www.screencast.com/t/HAeYUgOJTFfc

**Comment by Aqurds** [comment]
@Sheerazzafar "Terms and Conditions" & "Privacy policy" screens aren't included in the current milestone, so I haven't built those screens. Technically, it isn't a bug :) The link will be active and functional when I will build those screens in a future milestone.

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
Actually these screen are included in my testing milestone, I am leaving this task open for now, will close it in the next milestone when gets implemented.
Thanks.
cc: @romangorbunovCB

**Comment by romangorbunovCB** [comment]
@Aqurds 4 UT User - Terms and Conditions and 5 UT User - Privacy policy are actually included in the current milestone. Pls, make those screen with just a sample text. pls see the tasks assigned in the dashboard with the corresponding names for the features.
cc: @Sheerazzafar

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
Can you please also fix this task too.
Thanks!

**Comment by Aqurds** [comment]
@Sheerazzafar this task is fixed,
cc @romangorbunovCB

**Comment by Sheerazzafar** [comment]
Hi @Aqurds 
Verified this issue on latest build and this issue is still not fixed on latest build.

**Comment by Sheerazzafar** [comment]
Verified and fixed!
